--
-- DDL
--

DROP TABLE CATEGORIA PURGE;
DROP TABLE LOJA PURGE;
DROP TABLE RESPONSAVEL PURGE;
DROP TABLE ENDERECO PURGE;
DROP TABLE CATEGORIA_ITEM PURGE;
DROP TABLE ITEM PURGE;

DROP TRIGGER SYSTEM.CATEGORIA_BIR; 
DROP TRIGGER SYSTEM.LOJA_BIR;
DROP TRIGGER SYSTEM.RESPONSAVEL_BIR; 
DROP TRIGGER SYSTEM.ENDERECO_BIR;
DROP TRIGGER SYSTEM.CATEGORIA_ITEM_BIR; 
DROP TRIGGER SYSTEM.ITEM_BIR;

DROP SEQUENCE CATEGORIA_SEQ;
DROP SEQUENCE LOJA_SEQ;
DROP SEQUENCE RESPONSAVEL_SEQ;
DROP SEQUENCE ENDERECO_SEQ;
DROP SEQUENCE CATEGORIA_ITEM_SEQ;
DROP SEQUENCE ITEM_SEQ;

CREATE SEQUENCE CATEGORIA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LOJA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RESPONSAVEL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ENDERECO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CATEGORIA_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ITEM_SEQ START WITH 1 INCREMENT BY 1;


-- TABLE CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT NOT NULL,
    NM_CATEGORIA VARCHAR(75) NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA)
);

-- TABLE LOJA
CREATE TABLE LOJA (
    ID_LOJA INT NOT NULL,
    NR_CNPJ CHAR(18) NOT NULL,
    NM_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    NM_LOJA VARCHAR(100) NOT NULL,
    NR_TELEFONE CHAR(15) NOT NULL,
    DS_EMAIL VARCHAR(40) NOT NULL,
    CD_PLANO CHAR(1) NOT NULL,
    ID_CATEGORIA_LOJA INT NOT NULL,
    CONSTRAINT LOJA_PK PRIMARY KEY (ID_LOJA),
    CONSTRAINT LOJA_NR_CNPJ UNIQUE (NR_CNPJ),
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA_LOJA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- TABLE RESPONSAVEL
CREATE TABLE RESPONSAVEL (
    ID_RESPONSAVEL INT NOT NULL,
    NM_RESPONSAVEL VARCHAR(100) NOT NULL,
    NR_CPF CHAR(14) NOT NULL,
    NR_RG CHAR(12),
    ID_LOJA_RESPONSAVEL INT NOT NULL,
    CONSTRAINT RESPONSAVEL_PK PRIMARY KEY (ID_RESPONSAVEL),
    CONSTRAINT FK_LOJA_RESPONSAVEL FOREIGN KEY (ID_LOJA_RESPONSAVEL) REFERENCES LOJA(ID_LOJA)
);

-- TABLE ENDERECO
CREATE TABLE ENDERECO (
    ID_ENDERECO INT NOT NULL,
    NR_CEP CHAR(9) NOT NULL,
    CD_UF CHAR(2) NOT NULL,
    NM_CIDADE VARCHAR(50) NOT NULL,
    NM_BAIRRO VARCHAR(75) NOT NULL,
    NM_ENDERECO VARCHAR(100) NOT NULL,
    NR_NUMERO INT NOT NULL,
    DS_COMPLEMENTO VARCHAR(255),
    ID_LOJA_ENDERECO INT NOT NULL,
    CONSTRAINT ENDERECO_PK PRIMARY KEY (ID_ENDERECO),
    CONSTRAINT FK_LOJA_ENDERECO FOREIGN KEY (ID_LOJA_ENDERECO) REFERENCES LOJA(ID_LOJA)
);

-- TABLE CATEGORIA ITEM
CREATE TABLE CATEGORIA_ITEM (
    ID_CATEGORIA_ITEM INT NOT NULL,
    NM_CATEGORIA_ITEM VARCHAR(50) NOT NULL,
    CONSTRAINT ID_CATEGORIA_ITEM_PK PRIMARY KEY (ID_CATEGORIA_ITEM)
);

-- TABLE ITEM
CREATE TABLE ITEM (
    ID_ITEM INT NOT NULL,
    NM_ITEM VARCHAR(50) NOT NULL,
    DS_ITEM VARCHAR(250),
    VL_PRECO DECIMAL(18,2) NOT NULL,
    ID_LOJA_ITEM INT NOT NULL,
    ID_CATEGORIA_ITEM_ITEM INT NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (ID_ITEM),
    CONSTRAINT FK_LOJA_ITEM FOREIGN KEY (ID_LOJA_ITEM) REFERENCES LOJA(ID_LOJA),
    CONSTRAINT FK_CATEGORIA_ITEM_ITEM FOREIGN KEY (ID_CATEGORIA_ITEM_ITEM) REFERENCES CATEGORIA_ITEM(ID_CATEGORIA_ITEM)
);

-- TRIGGER CATEGORIA
CREATE OR REPLACE TRIGGER CATEGORIA_BIR 
    BEFORE INSERT ON CATEGORIA 
    FOR EACH ROW 
BEGIN 
    SELECT CATEGORIA_SEQ.NEXTVAL INTO :new.ID_CATEGORIA FROM dual;
END;
/

-- TRIGGER LOJA
CREATE OR REPLACE TRIGGER LOJA_BIR 
    BEFORE INSERT ON LOJA 
    FOR EACH ROW 
BEGIN 
    SELECT LOJA_SEQ.NEXTVAL INTO :new.ID_LOJA FROM dual;
END;
/

-- TRIGGER RESPONSAVEL
CREATE OR REPLACE TRIGGER RESPONSAVEL_BIR 
    BEFORE INSERT ON RESPONSAVEL 
    FOR EACH ROW 
BEGIN 
    SELECT RESPONSAVEL_SEQ.NEXTVAL INTO :new.ID_RESPONSAVEL FROM dual;
END;
/

-- TRIGGER ENDERECO
CREATE OR REPLACE TRIGGER ENDERECO_BIR 
    BEFORE INSERT ON ENDERECO 
    FOR EACH ROW 
BEGIN 
    SELECT ENDERECO_SEQ.NEXTVAL INTO :new.ID_ENDERECO FROM dual;
END;
/

-- TRIGGER CATEGORIA ITEM
CREATE OR REPLACE TRIGGER CATEGORIA_ITEM_BIR 
    BEFORE INSERT ON CATEGORIA_ITEM 
    FOR EACH ROW 
BEGIN 
    SELECT CATEGORIA_ITEM_SEQ.NEXTVAL INTO :new.ID_CATEGORIA_ITEM FROM dual;
END;
/

-- TRIGGER ITEM
CREATE OR REPLACE TRIGGER ITEM_BIR 
    BEFORE INSERT ON ITEM 
    FOR EACH ROW 
BEGIN 
    SELECT ITEM_SEQ.NEXTVAL INTO :new.ID_ITEM FROM dual;
END;
/

--
-- DML
--
INSERT INTO CATEGORIA (NM_CATEGORIA) VALUES ('Fast-Food');

INSERT INTO LOJA 
(NR_CNPJ, NM_RAZAO_SOCIAL, NM_LOJA, NR_TELEFONE, DS_EMAIL, CD_PLANO, ID_CATEGORIA_LOJA)
VALUES ('42.591.651/0001-43','Arcos Dourados Comércio de Alimentos Ltda.','McDonalds',
    '(16) 2719-3386','sac@sacmcdonalds.com.br',1,1);

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, NR_CPF, NR_RG, ID_LOJA_RESPONSAVEL)
VALUES ('Caleb Henry Anderson Jesus','279.309.438-28','34.922.152-2',1);

INSERT INTO ENDERECO 
(NR_CEP, CD_UF, NM_CIDADE, NM_BAIRRO, NM_ENDERECO, NR_NUMERO, DS_COMPLEMENTO, ID_LOJA_ENDERECO)
VALUES ('09520-110','SP','São Caetano do Sul','Fundação','Avenida Conde Francisco Matarazzo',607,NULL,1);

INSERT INTO CATEGORIA_ITEM (NM_CATEGORIA_ITEM) VALUES ('LANCHE');

INSERT INTO ITEM (NM_ITEM, DS_ITEM, VL_PRECO, ID_LOJA_ITEM, ID_CATEGORIA_ITEM_ITEM) 
VALUES ('MCOFERTA DUPLO CHEDDAR', 
    'Dois deliciosos hambúrgueres de carne bovina, 
    queijo tipo cheddar derretido, cebola ao molho shoyu no pão escuro com gergelim, acompanhamento e bebida',
    37.37, 1 ,1);